# Generated by Django 4.2.27 on 2026-01-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('standard', models.CharField(default='IATA', max_length=50)),
                ('example', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='server', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'System Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('vendor', models.CharField(max_length=200)),
                ('criticality', models.CharField(choices=[('CRITIQUE', 'Critique'), ('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('BASSE', 'Basse')], default='MOYENNE', max_length=20)),
                ('mode', models.CharField(choices=[('SAAS', 'SaaS'), ('CLOUD', 'Cloud Hébergé'), ('ONPREMISE', 'On-Premise'), ('INHOUSE', 'In-House'), ('RESEAU', 'Réseau')], default='ONPREMISE', max_length=20)),
                ('is_master_for', models.TextField(blank=True, help_text='Domaines de données dont ce système est la source de vérité')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='cartography.systemcategory')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='cartography.structure')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MessageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_start', models.IntegerField(blank=True, null=True)),
                ('position_end', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('field_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('example', models.CharField(blank=True, max_length=200)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('message_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cartography.messageformat')),
            ],
            options={
                'ordering': ['message_format', 'position_start', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('REALTIME', 'Temps réel'), ('CONTINUOUS', 'Continu'), ('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('BATCH', 'Batch'), ('ONDEMAND', 'À la demande')], default='DAILY', max_length=20)),
                ('protocol', models.CharField(choices=[('API_REST', 'API REST'), ('API_SOAP', 'API SOAP'), ('FILE', 'Fichier'), ('MESSAGE', 'Message IATA'), ('DATABASE', 'Base de données'), ('MANUAL', 'Manuel'), ('PROPRIETARY', 'Propriétaire')], default='PROPRIETARY', max_length=20)),
                ('format', models.CharField(blank=True, help_text='Format des données (SSIM, MVT, JSON, etc.)', max_length=100)),
                ('is_automated', models.BooleanField(default=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('volume', models.CharField(blank=True, help_text='Volume de données (ex: ~35 fichiers/jour)', max_length=100)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_flows', to='cartography.system')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_flows', to='cartography.system')),
            ],
            options={
                'ordering': ['source', 'target'],
            },
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('STRING', 'Chaîne'), ('INTEGER', 'Entier'), ('DECIMAL', 'Décimal'), ('DATE', 'Date'), ('DATETIME', 'Date/Heure'), ('BOOLEAN', 'Booléen'), ('ALPHANUM', 'Alphanumérique')], default='STRING', max_length=20)),
                ('length', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('example', models.CharField(blank=True, max_length=200)),
                ('position', models.IntegerField(blank=True, help_text='Position dans le message (pour formats positionnels)', null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cartography.dataflow')),
            ],
            options={
                'ordering': ['flow', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DataDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('criticality', models.CharField(default='HAUTE', max_length=20)),
                ('consumer_systems', models.ManyToManyField(blank=True, related_name='consumed_domains', to='cartography.system')),
                ('master_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastered_domains', to='cartography.system')),
            ],
        ),
    ]
