# Generated by Django 4.2.27 on 2026-01-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_system', models.CharField(choices=[('AIMS', 'AIMS'), ('AMADEUS', 'AMADEUS'), ('RAPID', 'RAPID'), ('ALTEA', 'ALTEA'), ('AMOS', 'AMOS'), ('ACCELYA', 'ACCELYA'), ('OTHER', 'Autre')], max_length=50)),
                ('data_type', models.CharField(choices=[('FLT', 'Flight Schedule (FLT)'), ('APS', 'Amadeus Payment (APS)'), ('PNR', 'PNR Data Feed'), ('FLP', 'FLP Transport'), ('IBP', 'Interline Billing (IBP)'), ('SLP', 'Sales Report (SLP)'), ('LIFT', 'LIFT File'), ('MVT', 'Movement Message'), ('SSIM', 'SSIM Schedule'), ('OTHER', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('sample_date', models.DateField(blank=True, help_text='Date des données échantillon', null=True)),
                ('record_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validé'), ('PARTIAL', 'Partiellement validé'), ('ISSUES', 'Problèmes détectés')], default='PENDING', max_length=20)),
                ('hypothesis_frequency', models.CharField(blank=True, max_length=50)),
                ('real_frequency', models.CharField(blank=True, max_length=50)),
                ('hypothesis_protocol', models.CharField(blank=True, max_length=50)),
                ('real_protocol', models.CharField(blank=True, max_length=50)),
                ('hypothesis_format', models.CharField(blank=True, max_length=100)),
                ('real_format', models.CharField(blank=True, max_length=100)),
                ('hypothesis_volume', models.CharField(blank=True, max_length=100)),
                ('real_volume', models.CharField(blank=True, max_length=100)),
                ('fields_confirmed', models.IntegerField(default=0)),
                ('fields_with_issues', models.IntegerField(default=0)),
                ('fields_new_discovered', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='cartography.dataflow')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_validations', to='cartography.datasample')),
            ],
            options={
                'ordering': ['-validated_at'],
                'unique_together': {('flow', 'sample')},
            },
        ),
        migrations.CreateModel(
            name='FlowFieldHypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('hypothesis_type', models.CharField(blank=True, help_text='Type supposé', max_length=50)),
                ('hypothesis_format', models.CharField(blank=True, help_text='Format supposé', max_length=200)),
                ('hypothesis_description', models.TextField(blank=True)),
                ('hypothesis_example', models.CharField(blank=True, max_length=500)),
                ('real_type', models.CharField(blank=True, max_length=50)),
                ('real_format', models.CharField(blank=True, max_length=200)),
                ('real_description', models.TextField(blank=True)),
                ('real_example', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('HYPOTHESIS', 'Hypothèse'), ('CONFIRMED', 'Confirmé'), ('PARTIAL', 'Partiellement confirmé'), ('INCORRECT', 'Incorrect')], default='HYPOTHESIS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_hypotheses', to='cartography.dataflow')),
                ('validated_from_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartography.datasample')),
            ],
            options={
                'ordering': ['flow', 'field_name'],
                'unique_together': {('flow', 'field_name')},
            },
        ),
    ]
