# Generated by Django 4.2.27 on 2026-01-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0002_datasample_flowvalidation_flowfieldhypothesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasample',
            name='column_stats_json',
            field=models.JSONField(blank=True, default=dict, help_text='Stats par colonne (type, exemples)'),
        ),
        migrations.AddField(
            model_name='datasample',
            name='columns_json',
            field=models.JSONField(blank=True, default=list, help_text='Liste des colonnes découvertes'),
        ),
        migrations.AddField(
            model_name='datasample',
            name='sample_rows_json',
            field=models.JSONField(blank=True, default=list, help_text="Quelques lignes d'exemple"),
        ),
    ]
