# Generated by Django 5.2.10 on 2026-01-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0003_datasample_column_stats_json_datasample_columns_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('referential_type', models.CharField(choices=[('CODE', 'Code de référence'), ('TABLE', 'Table de correspondance'), ('ENUM', 'Énumération'), ('STANDARD', 'Standard (IATA, ISO, etc.)'), ('INTERNAL', 'Référentiel interne')], default='CODE', max_length=20)),
                ('standard', models.CharField(blank=True, help_text='Standard de référence (IATA, ISO, etc.)', max_length=100)),
                ('example_values', models.JSONField(blank=True, default=list, help_text='Exemples de valeurs')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Référentiel obligatoire pour les flux')),
                ('documentation_url', models.URLField(blank=True)),
                ('master_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_referentials', to='cartography.system')),
            ],
            options={
                'verbose_name': 'Référentiel',
                'verbose_name_plural': 'Référentiels',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FlowReferential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(choices=[('INPUT', 'Entrée'), ('OUTPUT', 'Sortie'), ('VALIDATION', 'Validation'), ('TRANSFORMATION', 'Transformation')], default='INPUT', max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Champ du flux utilisant ce référentiel', max_length=100)),
                ('is_present_in_sample', models.BooleanField(default=False, help_text='Référentiel présent dans les échantillons')),
                ('notes', models.TextField(blank=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referentials', to='cartography.dataflow')),
                ('reference_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_flows', to='cartography.referencedata')),
            ],
            options={
                'ordering': ['flow', 'reference_data'],
                'unique_together': {('flow', 'reference_data', 'field_name')},
            },
        ),
    ]
