# Generated by Django 5.2.10 on 2026-01-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0004_referencedata_flowreferential'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='country',
            field=models.CharField(choices=[('DZ', 'Algérie'), ('FR', 'France'), ('ES', 'Espagne'), ('US', 'États-Unis'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('CH', 'Suisse'), ('BE', 'Belgique'), ('NL', 'Pays-Bas'), ('AE', 'Émirats Arabes Unis'), ('SA', 'Arabie Saoudite'), ('MA', 'Maroc'), ('TN', 'Tunisie'), ('TR', 'Turquie'), ('IT', 'Italie'), ('SG', 'Singapour'), ('IN', 'Inde'), ('INTL', 'International'), ('OTHER', 'Autre')], default='DZ', help_text="Pays d'origine de la structure", max_length=10),
        ),
        migrations.AddField(
            model_name='system',
            name='country',
            field=models.CharField(choices=[('DZ', 'Algérie'), ('FR', 'France'), ('ES', 'Espagne'), ('US', 'États-Unis'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('CH', 'Suisse'), ('BE', 'Belgique'), ('NL', 'Pays-Bas'), ('AE', 'Émirats Arabes Unis'), ('SA', 'Arabie Saoudite'), ('MA', 'Maroc'), ('TN', 'Tunisie'), ('TR', 'Turquie'), ('IT', 'Italie'), ('SG', 'Singapour'), ('IN', 'Inde'), ('INTL', 'International'), ('OTHER', 'Autre')], default='DZ', help_text="Pays d'origine du système/éditeur", max_length=10),
        ),
    ]
