# Generated by Django 5.2.10 on 2026-02-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0005_structure_country_system_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('import_type', models.CharField(choices=[('DATAFEED', 'Datafeeds'), ('SYSTEM', 'Systèmes'), ('FLOW', 'Flux de données'), ('FORMAT', 'Formats de messages'), ('SAMPLE', 'Échantillons'), ('REFERENTIAL', 'Référentiels'), ('OTHER', 'Autre')], default='DATAFEED', max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Succès'), ('PARTIAL', 'Partiel'), ('FAILED', 'Échec')], default='SUCCESS', max_length=20)),
                ('source_folder', models.CharField(blank=True, help_text='Dossier source des données', max_length=500)),
                ('systems_added', models.IntegerField(default=0)),
                ('flows_added', models.IntegerField(default=0)),
                ('formats_added', models.IntegerField(default=0)),
                ('fields_added', models.IntegerField(default=0)),
                ('samples_added', models.IntegerField(default=0)),
                ('details_json', models.JSONField(blank=True, default=dict, help_text='Détails des éléments ajoutés')),
                ('files_processed', models.JSONField(blank=True, default=list, help_text='Liste des fichiers traités')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Historique d'import",
                'verbose_name_plural': "Historiques d'imports",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='structure',
            name='country',
            field=models.CharField(choices=[('DZ', 'Algérie'), ('FR', 'France'), ('EU', 'Europe (autre)'), ('INTL', 'International/Cloud')], default='DZ', help_text='Pays où la structure est localisée', max_length=10),
        ),
        migrations.AlterField(
            model_name='system',
            name='country',
            field=models.CharField(choices=[('DZ', 'Algérie'), ('FR', 'France'), ('EU', 'Europe (autre)'), ('INTL', 'International/Cloud')], default='DZ', help_text='Pays où le système est installé/hébergé', max_length=10),
        ),
    ]
