# Generated by Django 5.2.10 on 2026-02-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0006_dataimporthistory_alter_structure_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=200)),
                ('phase', models.IntegerField(choices=[(1, 'Phase 1 — Critique 🔴'), (2, 'Phase 2 — Important 🟠'), (3, 'Phase 3 — Standard 🟢')], default=1)),
                ('priority_in_phase', models.IntegerField(default=1)),
                ('editor', models.CharField(blank=True, max_length=200)),
                ('direction', models.CharField(blank=True, max_length=200)),
                ('key_users', models.TextField(blank=True, help_text='Key Users principaux')),
                ('key_users_backup', models.TextField(blank=True, help_text='Key Users backup')),
                ('responsible', models.TextField(blank=True, help_text='Responsable hiérarchique')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non commencé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé')], default='NOT_STARTED', max_length=20)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='cartography.system')),
            ],
            options={
                'ordering': ['phase', 'priority_in_phase'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cartography.questionnaire')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Numéro de la question (Q1, Q2...)', max_length=10)),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text="Notes prises pendant l'entretien")),
                ('is_answered', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cartography.questionsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
