# Generated by Django 5.2.10 on 2026-03-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0007_questionnaire_questionsection_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='revision_history',
            field=models.JSONField(blank=True, default=list, help_text='Historique des modifications'),
        ),
        migrations.AddField(
            model_name='question',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='validated_by',
            field=models.CharField(blank=True, help_text='Nom du validateur', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='validation_comment',
            field=models.TextField(blank=True, help_text='Commentaire de validation ou motif de rejet'),
        ),
        migrations.AddField(
            model_name='question',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATED', 'Validée'), ('REJECTED', 'Rejetée / À revoir'), ('REVISED', 'Révisée')], default='PENDING', max_length=20),
        ),
    ]
