# Generated by Django 5.2.10 on 2026-03-15 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0008_question_revision_history_question_validated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du key user', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='cartography.questionnaire')),
            ],
            options={
                'verbose_name': 'Accès Key User',
                'verbose_name_plural': 'Accès Key Users',
                'ordering': ['questionnaire', 'name'],
            },
        ),
    ]
