# Generated by Django 5.2.10 on 2026-03-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0009_keyuseraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, help_text='Pièce jointe (PDF, image, document...)', null=True, upload_to='question_attachments/'),
        ),
    ]
