# Generated by Django 5.2.10 on 2026-03-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0010_question_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'auditeur", max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Accès Auditeur',
                'verbose_name_plural': 'Accès Auditeurs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='auditor_comment',
            field=models.TextField(blank=True, help_text="Commentaire de l'auditeur"),
        ),
        migrations.AddField(
            model_name='question',
            name='auditor_comment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='auditor_comment_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='structure',
            name='level',
            field=models.CharField(blank=True, default='', help_text='Niveau hiérarchique (PDG, DGA, Direction, Sous-direction, Service)', max_length=30),
        ),
        migrations.AddField(
            model_name='structure',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Structure parente (ex: Direction parente d'un Service)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cartography.structure'),
        ),
        migrations.AddField(
            model_name='structure',
            name='responsable',
            field=models.CharField(blank=True, help_text='Nom du responsable de la structure', max_length=200),
        ),
    ]
