# Generated by Django 5.2.10 on 2026-04-06 08:19

from django.db import migrations


def fix_direction_names(apps, schema_editor):
    Structure = apps.get_model('cartography', 'Structure')
    updates = {
        'DSC': 'Direction de la Surveillance de la Conformité',
        'DAGP': 'Direction Achat et Gestion du Patrimoine',
        'DMRA': 'Direction Maintenance & Réparations des Aéronefs',
    }
    for code, new_name in updates.items():
        Structure.objects.filter(code=code).update(name=new_name)


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0011_auditoraccess_question_auditor_comment_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_direction_names, migrations.RunPython.noop),
    ]
