# Generated by Django 5.2.10 on 2026-04-06 08:44

from django.db import migrations


def fix_divisions_powerbi_dpd(apps, schema_editor):
    Structure = apps.get_model('cartography', 'Structure')
    System = apps.get_model('cartography', 'System')

    # 1) Direction → Division pour DAG, DC, DIVEX, DMRA
    renames = {
        'DAG': 'Division des Affaires Générales',
        'DC': 'Division Commerciale',
        'DIVEX': "Division de l'Exploitation",
        'DMRA': 'Division Maintenance & Réparations des Aéronefs',
    }
    for code, new_name in renames.items():
        Structure.objects.filter(code=code).update(name=new_name)

    # 2) Power BI: DSI → DRH
    drh = Structure.objects.get(code='DRH')
    System.objects.filter(code='POWERBI').update(structure=drh)

    # 3) DPD: parent DIVEX → DG, couleur rouge
    dg = Structure.objects.get(code='DG')
    Structure.objects.filter(code='DPD').update(parent=dg, color='#ef4444')


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0012_fix_direction_names'),
    ]

    operations = [
        migrations.RunPython(fix_divisions_powerbi_dpd, migrations.RunPython.noop),
    ]
