# Generated by Django 5.2.10 on 2026-04-07 15:57

from django.db import migrations


def reset_sage_stock(apps, schema_editor):
    Questionnaire = apps.get_model('cartography', 'Questionnaire')
    Question = apps.get_model('cartography', 'Question')

    q = Questionnaire.objects.get(system__code='SAGE-STOCK')
    Question.objects.filter(section__questionnaire=q).update(answer='')
    q.status = 'NOT_STARTED'
    q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0013_fix_divisions_powerbi_dpd'),
    ]

    operations = [
        migrations.RunPython(reset_sage_stock, migrations.RunPython.noop),
    ]
