# Generated by Django 5.2.10 on 2026-04-07 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0014_reset_sage_stock_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du responsable division', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('structure', models.ForeignKey(help_text='Division rattachée', on_delete=django.db.models.deletion.CASCADE, related_name='division_tokens', to='cartography.structure')),
            ],
            options={
                'verbose_name': 'Accès Division',
                'verbose_name_plural': 'Accès Divisions',
                'ordering': ['structure', 'name'],
            },
        ),
    ]
