# Generated by Django 5.2.10 on 2026-04-07 16:11

from django.db import migrations


DIVISION_TOKENS = [
    ('DAG', 'Responsable DAG', 'fdG-VGn41Q09NyY32Hga5MU72hlhI3vymamoLghcHO8'),
    ('DC', 'Responsable DC', 'BhZk-brHLhhESE19VlVpCY-Ye4873jQd5AYCkSCJRfM'),
    ('DIVEX', 'Responsable DIVEX', 'c7I4Qd6GbIUWb_AcImsPR5ZMwEI8Irj3AMDoHpDAMTo'),
    ('DMRA', 'Responsable DMRA', 'PLi5w-XTHzNwzh6ho5mjN1o6KebUmn4c1PQV817RwvE'),
]


def create_division_tokens(apps, schema_editor):
    Structure = apps.get_model('cartography', 'Structure')
    DivisionAccess = apps.get_model('cartography', 'DivisionAccess')
    for code, name, token in DIVISION_TOKENS:
        struct = Structure.objects.get(code=code)
        DivisionAccess.objects.get_or_create(
            structure=struct,
            defaults={'name': name, 'token': token}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0015_add_division_access'),
    ]

    operations = [
        migrations.RunPython(create_division_tokens, migrations.RunPython.noop),
    ]
