# Generated by Django 5.2.10 on 2026-04-08 10:02

from django.db import migrations


AUDITOR_PROFILES = [
    ('M. le PDG', '', 'O1rsN-PB1BKO8v6np1Bg0Bg6NoSBN00PkgutOn7G69M'),
    ('DOUMI Nabil (Conseiller PDG)', 'doumi.nabil@airalgerie.dz', 'OaNymGx3ZeBWZTBxFqCd6CVuqcm_hEeuBNvFoJ7EnXo'),
]

DIVISION_PROFILES = [
    ('DAG', 'Mme la DAG', '', 'qYymtXBumq3o0BDdFvyO74FjwWuqn_8XeutquSSmUBg'),
    ('DC', 'BOUTEMADJA Samy', 'boutemadja.samy@airalgerie.dz', '1gZ_9JMxC0QTcY9XyHCYFeWW7YzDtWO0-OCt48MHqOM'),
    ('DIVEX', 'BENBOUAZIZ Lyes', 'benbouaziz.lyes@airalgerie.dz', 'LYmlpP9IWIPM9d6A7gXxvwK3hu3a41a9UsjSApbzGlo'),
    ('DMRA', 'HACHELAF Mourad', 'hachelaf.mourad@airalgerie.dz', 'zmgCAn1EI7h_DL-FaxRuXrQrmynXYE07JWj648p69Jk'),
    ('DRH', 'KRAIMECHE Abdelkrim', 'kraimeche.abdelkrim@airalgerie.dz', '0aLgUODgi580CWOUbNbPvVYMqEGScp0AK_gWTN7OziE'),
    ('DSI', 'DEBAB', '', 'MS14bS1w8jrKtxr2KGbnPwiJIw2nZ1XVkWlq95buRss'),
    ('DSI', 'MERDACI Adel', 'merdaci.adel@airalgerie.dz', 'kb2HMNgtwGkzrCuD10rk9dOwY_EtvkdBvhkS_exprXY'),
    ('DVR', 'BOUNAB Nihad', 'bounab.nihad@airalgerie.dz', '250LRTA7DV2_-_Tk-tdD8e21l69xNXlNwvvnWtF1fvU'),
    ('DRM', 'FAIDI Fouad', 'faidi.fouad@airalgerie.dz', 'rtZgim5mm0vasK8hBIm_s4GDlMUAJ7HN-RErx7826qc'),
    ('DFC', 'KHELFI Redouane', 'khelfi.redouane@airalgerie.dz', 'JazLAOvgbFrMX1BLGxN19AzasbuiHzfyx3lNBO-A00o'),
    ('DOA', 'BENBOUAZIZ Lyes (DOA)', 'benbouaziz.lyes@airalgerie.dz', 'ZEIdYfcQC3_AXTHwImCV1H8ZNSE-KKSsqLAJABD37Fc'),
]


def create_personalized_access(apps, schema_editor):
    Structure = apps.get_model('cartography', 'Structure')
    AuditorAccess = apps.get_model('cartography', 'AuditorAccess')
    DivisionAccess = apps.get_model('cartography', 'DivisionAccess')

    # Supprimer les anciens tokens division génériques
    DivisionAccess.objects.all().delete()

    # Créer accès admin (PDG + Conseiller)
    for name, email, token in AUDITOR_PROFILES:
        AuditorAccess.objects.get_or_create(
            token=token,
            defaults={'name': name, 'email': email}
        )

    # Créer accès division/direction personnalisés
    for code, name, email, token in DIVISION_PROFILES:
        struct = Structure.objects.get(code=code)
        DivisionAccess.objects.get_or_create(
            token=token,
            defaults={'structure': struct, 'name': name, 'email': email}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0016_create_division_tokens'),
    ]

    operations = [
        migrations.RunPython(create_personalized_access, migrations.RunPython.noop),
    ]
