# Generated by Django 5.2.10 on 2026-04-12 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0018_edoleance_dvr_dag_auditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(help_text='Code court (ex: PROC-WT-001)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description courte du process')),
                ('context', models.TextField(blank=True, help_text='Description complète en langage naturel (entretien)')),
                ('category', models.CharField(choices=[('OPERATIONAL', 'Opérationnel'), ('SUPPORT', 'Support'), ('MANAGEMENT', 'Management'), ('COMMERCIAL', 'Commercial'), ('MAINTENANCE', 'Maintenance'), ('FINANCE', 'Finance'), ('HR', 'Ressources Humaines'), ('IT', 'Informatique'), ('OTHER', 'Autre')], default='OPERATIONAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('DOCUMENTED', 'Documenté'), ('VALIDATED', 'Validé'), ('TO_BE', 'Cible (TO-BE)')], default='DRAFT', max_length=20)),
                ('problems', models.TextField(blank=True, help_text='Problèmes et dysfonctionnements identifiés')),
                ('recommendations', models.TextField(blank=True, help_text="Recommandations d'amélioration")),
                ('workflow_json', models.JSONField(blank=True, default=dict, help_text='Workflow structuré (nœuds + arêtes)')),
                ('workflow_mermaid', models.TextField(blank=True, help_text='Code Mermaid du diagramme')),
                ('ai_generated', models.BooleanField(default=False, help_text='Workflow généré par IA')),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='cartography.questionnaire')),
                ('structures', models.ManyToManyField(blank=True, help_text='Structures impactées', related_name='processes', to='cartography.structure')),
                ('systems', models.ManyToManyField(blank=True, help_text='Systèmes impliqués', related_name='processes', to='cartography.system')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Process',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('MANUAL', 'Action manuelle'), ('AUTOMATED', 'Action automatisée'), ('DECISION', 'Point de décision'), ('INPUT', 'Entrée / Déclencheur'), ('OUTPUT', 'Sortie / Résultat'), ('WAIT', 'Attente / Délai'), ('PARALLEL', 'Actions parallèles')], default='MANUAL', max_length=20)),
                ('actor_role', models.CharField(blank=True, help_text='Poste/rôle responsable', max_length=200)),
                ('data_inputs', models.TextField(blank=True, help_text='Données en entrée')),
                ('data_outputs', models.TextField(blank=True, help_text='Données en sortie')),
                ('interactions', models.TextField(blank=True, help_text='Interactions (homme↔système, système↔système, etc.)')),
                ('problems', models.TextField(blank=True, help_text='Problèmes spécifiques à cette étape')),
                ('duration_estimate', models.CharField(blank=True, help_text='Durée estimée', max_length=100)),
                ('next_steps', models.JSONField(blank=True, default=list, help_text='IDs des étapes suivantes (pour branches)')),
                ('actor_structure', models.ForeignKey(blank=True, help_text='Structure responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartography.structure')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cartography.process')),
                ('systems_used', models.ManyToManyField(blank=True, help_text='Systèmes utilisés à cette étape', related_name='process_steps', to='cartography.system')),
            ],
            options={
                'ordering': ['process', 'order'],
            },
        ),
    ]
