# Generated by Django 5.2.10 on 2026-04-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0025_split_q40_per_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_index=True, help_text='Ex: KU001', max_length=20, unique=True)),
                ('variants', models.JSONField(default=list, help_text='Liste de variantes de noms à rechercher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Correspondance matricule',
                'verbose_name_plural': 'Correspondances matricules',
                'ordering': ['matricule'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='attachment_anonymized',
            field=models.BooleanField(default=False, help_text='Contenu anonymisé (texte)'),
        ),
        migrations.AddField(
            model_name='question',
            name='attachment_content_type',
            field=models.CharField(blank=True, help_text='Type MIME', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='attachment_data',
            field=models.BinaryField(blank=True, help_text='Contenu binaire de la pièce jointe (anonymisé si possible)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='attachment_filename',
            field=models.CharField(blank=True, help_text='Nom de fichier original', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, help_text='Taille en octets (après anonymisation)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='attachment_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, help_text='[DÉPRÉCIÉ] utiliser attachment_data', null=True, upload_to='question_attachments/'),
        ),
    ]
