# Generated by Django 5.2.10 on 2026-04-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0026_add_attachment_binary_and_matriculemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('ACCESS', 'Accès à mes données'), ('RECTIFICATION', 'Rectification'), ('DELETION', 'Suppression'), ('OPPOSITION', 'Opposition au traitement'), ('LIMITATION', 'Limitation du traitement'), ('PORTABILITY', 'Portabilité')], max_length=20)),
                ('requester_name', models.CharField(max_length=200)),
                ('requester_email', models.EmailField(max_length=254)),
                ('requester_identifier', models.CharField(blank=True, help_text='Matricule, fonction, numéro employé...', max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours de traitement'), ('RESOLVED', 'Résolue'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('responded_by', models.CharField(blank=True, max_length=200)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Demande d'exercice des droits",
                'verbose_name_plural': "Demandes d'exercice des droits",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Échec de connexion'), ('LOGOUT', 'Déconnexion'), ('TOKEN_ACCESS', 'Accès par token'), ('TOKEN_INVALID', 'Token invalide'), ('VIEW_QUESTIONNAIRE', 'Consultation questionnaire'), ('VIEW_SYSTEM', 'Consultation système'), ('VIEW_FLOW', 'Consultation flux'), ('SUBMIT_ANSWER', 'Soumission réponse'), ('VALIDATE_ANSWER', 'Validation réponse'), ('UPLOAD_ATTACHMENT', 'Upload pièce jointe'), ('DOWNLOAD_ATTACHMENT', 'Téléchargement pièce jointe'), ('EXPORT', 'Export de données'), ('RIGHTS_REQUEST', 'Demande exercice des droits'), ('ADMIN_ACTION', 'Action administrative'), ('OTHER', 'Autre')], db_index=True, max_length=30)),
                ('actor', models.CharField(blank=True, help_text='Utilisateur (username ou matricule ou anonyme)', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, help_text='Type de ressource consultée (questionnaire, system, question...)', max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Contexte additionnel (JSON)')),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='cartography_timesta_3286c6_idx'), models.Index(fields=['action', '-timestamp'], name='cartography_action_970808_idx'), models.Index(fields=['actor', '-timestamp'], name='cartography_actor_47bd8c_idx')],
            },
        ),
    ]
