# Generated by Django 5.2.10 on 2026-05-17 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0027_add_audit_log_and_rights_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='validated_by',
            field=models.CharField(blank=True, help_text='Nom du dernier validateur', max_length=200),
        ),
        migrations.AddField(
            model_name='process',
            name='validated_role',
            field=models.CharField(blank=True, help_text='Fonction du validateur (Directeur, Chef de division...)', max_length=200),
        ),
        migrations.AddField(
            model_name='process',
            name='validation_comment',
            field=models.TextField(blank=True, help_text='Commentaire du validateur'),
        ),
        migrations.AddField(
            model_name='process',
            name='validation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='validation_requested_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='process',
            name='validation_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Non demandée'), ('PENDING', 'En attente de validation'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté'), ('REVISION_REQUESTED', 'Révision demandée')], default='NOT_REQUESTED', help_text='Statut actuel du circuit de validation', max_length=25),
        ),
        migrations.AddField(
            model_name='process',
            name='validation_token',
            field=models.UUIDField(blank=True, help_text="Token d'accès public unique permettant aux validateurs externes de valider sans compte", null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProcessValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REQUESTED', 'Soumission pour validation'), ('APPROVED', 'Validation accordée'), ('REJECTED', 'Rejet'), ('REVISION_REQUESTED', 'Révision demandée'), ('CANCELLED', 'Demande annulée')], max_length=25)),
                ('actor_name', models.CharField(help_text='Nom du validateur ou du demandeur (saisi sur la page publique de validation)', max_length=200)),
                ('actor_role', models.CharField(blank=True, help_text='Fonction du validateur (Directeur, Chef de division, etc.)', max_length=200)),
                ('comment', models.TextField(blank=True, help_text='Commentaire libre')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('process', models.ForeignKey(help_text='Process concerné', on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='cartography.process')),
                ('structure', models.ForeignKey(blank=True, help_text="Structure au nom de laquelle l'action a été effectuée", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_validations', to='cartography.structure')),
            ],
            options={
                'verbose_name': 'Action de validation',
                'verbose_name_plural': 'Historique de validation',
                'ordering': ['-created_at'],
            },
        ),
    ]
