# Generated by Django 5.2.10 on 2026-05-17 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0028_process_validated_at_process_validated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStructureValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validée'), ('REJECTED', 'Rejetée'), ('REVISION_REQUESTED', 'Révision demandée')], db_index=True, default='PENDING', max_length=25)),
                ('token', models.UUIDField(default=uuid.uuid4, help_text="Token public unique pour cette structure (lien d'invitation par mail)", unique=True)),
                ('validated_by', models.CharField(blank=True, help_text='Nom du validateur', max_length=200)),
                ('validated_role', models.CharField(blank=True, help_text='Fonction du validateur', max_length=200)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, help_text='Commentaire du validateur')),
                ('last_reminder_at', models.DateTimeField(blank=True, help_text='Dernière relance envoyée', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(help_text='Process concerné', on_delete=django.db.models.deletion.CASCADE, related_name='structure_validations', to='cartography.process')),
                ('structure', models.ForeignKey(help_text='Structure responsable de cette validation', on_delete=django.db.models.deletion.CASCADE, related_name='pending_process_validations', to='cartography.structure')),
            ],
            options={
                'verbose_name': 'Validation par structure',
                'verbose_name_plural': 'Validations par structure',
                'ordering': ['process__code', 'structure__code'],
                'unique_together': {('process', 'structure')},
            },
        ),
    ]
