# Generated by Django 5.2.10 on 2026-05-25 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography', '0029_process_structure_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création du process'), ('UPDATE_FIELDS', 'Modification de champs'), ('ADD_STEP', "Ajout d'une étape"), ('EDIT_STEP', "Modification d'une étape"), ('DELETE_STEP', "Suppression d'une étape"), ('REORDER_STEPS', 'Réordonnancement des étapes'), ('EDIT_MERMAID', 'Édition manuelle du diagramme Mermaid'), ('REGEN_MERMAID', 'Régénération du diagramme (statique)'), ('REGEN_AI', 'Régénération du workflow par IA')], db_index=True, max_length=20)),
                ('editor_type', models.CharField(choices=[('STAFF', 'Administrateur'), ('DIVISION', 'Chef de division'), ('KEY_USER', 'Key User responsable'), ('SYSTEM', 'Système / Script')], default='STAFF', max_length=15)),
                ('editor_name', models.CharField(help_text="Nom complet de l'éditeur", max_length=200)),
                ('editor_role', models.CharField(blank=True, help_text='Rôle / fonction', max_length=200)),
                ('step_label', models.CharField(blank=True, help_text="Libellé de l'étape au moment de l'action (gardé même si l'étape est supprimée)", max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Détail des modifications. Structure conseillée : {'fields': {'name': {'old': 'A', 'new': 'B'}, ...}, 'note': 'libre'}")),
                ('summary', models.CharField(blank=True, help_text="Résumé court lisible (ex : 'Titre + 2 champs modifiés')", max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('editor_key_user', models.ForeignKey(blank=True, help_text='Token KeyUser utilisé (KEY_USER)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_edits', to='cartography.keyuseraccess')),
                ('editor_structure', models.ForeignKey(blank=True, help_text="Division au nom de laquelle l'édition est faite (DIVISION)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_edits', to='cartography.structure')),
                ('editor_user', models.ForeignKey(blank=True, help_text='Compte Django si STAFF', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_edits', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(help_text='Process modifié', on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='cartography.process')),
                ('step', models.ForeignKey(blank=True, help_text='Étape concernée (pour ADD_STEP/EDIT_STEP/DELETE_STEP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to='cartography.processstep')),
            ],
            options={
                'verbose_name': "Journal d'édition de process",
                'verbose_name_plural': 'Journal des éditions de process',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['process', '-created_at'], name='cartography_process_1d7b3f_idx'), models.Index(fields=['editor_type', '-created_at'], name='cartography_editor__bdbc60_idx')],
            },
        ),
    ]
